name: CI/CD Frontend

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/repo-frontend:latest

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Crear docker-compose en EC2
        run: |
          COMPOSE_CONTENT=$(cat docker-compose.yml | base64 -w 0)
          aws ssm send-command \
            --instance-ids "i-034188b32f54ef080" \
            --document-name "AWS-RunShellScript" \
            --parameters commands=["echo $COMPOSE_CONTENT | base64 -d > /home/ssm-user/docker-compose.yml"]

      - name: Ejecutar deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-034188b32f54ef080" \
            --document-name "AWS-RunShellScript" \
            --parameters commands='["docker pull ${{ secrets.DOCKERHUB_USERNAME }}/repo-frontend:latest","docker ps -q --filter \"publish=80\" | xargs -r docker rm -f || true","cd /home/ssm-user && docker compose pull && docker compose up -d --remove-orphans"]'