name: CI/CD Frontend - EKS

on:
  push:
    branches:
      - deploy

env:
  ECR_REPO: innovatech-frontend
  EKS_NAMESPACE: innovatech
  DEPLOYMENT_NAME: frontend
  CONTAINER_NAME: frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir tag de imagen
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build y push imagen
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            --build-arg VITE_API_DESPACHOS_URL=${{ secrets.VITE_API_DESPACHOS_URL }} \
            --build-arg VITE_API_VENTAS_URL=${{ secrets.VITE_API_VENTAS_URL }} \
            -t $ECR_REGISTRY/${ECR_REPO}:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/${ECR_REPO}:${IMAGE_TAG}

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.31.0

      - name: Configurar kubeconfig para EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}
          kubectl config current-context

      - name: Aplicar manifests base
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl  apply -f k8s/

      - name: Actualizar imagen del deployment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          kubectl set image deployment/${DEPLOYMENT_NAME} \
            ${CONTAINER_NAME}=$ECR_REGISTRY/${ECR_REPO}:${IMAGE_TAG} \
            -n ${EKS_NAMESPACE}
          kubectl rollout status deployment/${DEPLOYMENT_NAME} -n ${EKS_NAMESPACE}

      - name: Ver estado final
        run: |
          kubectl get pods -n ${EKS_NAMESPACE}
          kubectl get svc -n ${EKS_NAMESPACE}
